# Biblioteca NumPy

NumPy es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

Sus características principales son:
- **Matrices N-dimensionales potentes:** Rápidas y versátiles, los conceptos de vectorización, indexación y broadcasting de NumPy son los estándares de facto de la informática matricial actual.
- **Herramientas de cómputo numérico:** NumPy ofrece funciones matemáticas completas, generadores de números aleatorios, rutinas de álgebra lineal, transformadas de Fourier y más.
- **Interoperable:** NumPy es compatible con una amplia gama de plataformas de hardware y computación, y funciona bien con bibliotecas distribuidas, de GPU y de matrices dispersas.
- **Alto rendimiento:** El núcleo de NumPy es un código C bien optimizado.
- **Fácil de usar:** La sintaxis de alto nivel de NumPy lo hace accesible y productivo para programadores de cualquier nivel de formación o experiencia.

Instala la biblioteca `numpy`...

Esta libreta consiste principalmente de código. Agrega tus notas y observaciones en celdas con formato Markdown.

In [2]:
import numpy as np

In [3]:
np.__version__

'2.0.2'

## Funciones para crear arreglos

In [3]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
x = np.array([1, 4, 2, 5, 3])
x.dtype

dtype('int64')

In [5]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
x = np.array([3.14, 4, 2, 3])
x.dtype

dtype('float64')

In [7]:
np.array([1, 2, 3, 4], dtype='float64')

array([1., 2., 3., 4.])

In [8]:
np.array([1.2, 2, 3, 4], dtype='int64')

array([1, 2, 3, 4])

In [12]:
np.array([200, 300, 400, 500], dtype='int8')

OverflowError: Python integer 200 out of bounds for int8

In [13]:
np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]

In [15]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [16]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
x = np.zeros(10, dtype="int")
x.dtype

dtype('int64')

In [18]:
np.zeros(10, dtype="str")

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [19]:
x = np.zeros(10, dtype="str")
x.dtype

dtype('<U1')

In [20]:
np.ones((3, 5), dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
x = np.ones((3, 5), dtype="float")
x.dtype

dtype('float64')

In [22]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

**Ejercicio:** Utilizando el sistema de ayuda incorporado de Python y Jupyter, escribe con tus propias palabras qué hacen las siguientes funciones y presenta ejemplos.
- `np.eye`
- `np.identity`

In [23]:
? np.eye

Signature:
 np.eye(
    N,
    M=None,
    k=0,
    dtype=<class 'float'>,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Referenc

La función np.eye, es una generalización de una matriz identidad, pro lo que en lugar de devolver matrices cuadradas, podemos proporcionarle un valo m que sea el valor de las columnas, otras propiedades que tiene esta funcion,tambien si definimos un valor k podemos mover la diagonal ya sea para la parte superior, como la inferior, el like aun no lo entiendo.

In [24]:
? np.identity

Signature:  np.identity(n, dtype=None, *, like=None)
Docstring:
Return the identity array.

The identity array is a square array with ones on
the main diagonal.

Parameters
----------
n : int
    Number of rows (and columns) in `n` x `n` output.
dtype : data-type, optional
    Data-type of the output.  Defaults to ``float``.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    `n` x `n` array with its main diagonal set to one,
    and all other elements 0.

Examples
--------
>>> np.identity(3)
array([[1.,  0.,  0.],
       [0.,  1.,  0.],
       [0.,  0.,  1.]])
File:      /opt/conda/lib/python3.11/site-packages/numpy/_core/numer

Es dar la matriz identidad diciendole la dimensión de la misma.

## Intervalos de valores

In [25]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
x = np.linspace(0,1,10)
len(x)

10

In [27]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x = np.arange(0,100,10)
len(x)

In [ ]:
np.arange(0,1,0.1)

In [ ]:
range(0,1,0.1)

**Ejercicio:** Implementa una función llamada `float_range` que sea como `range` pero que funcione con valores flotantes.

In [46]:
def range_float(*args):
    if not all(isinstance(arg, (int, float)) for arg in args):
        raise ValueError("Se esperan datos numéricos.")
        
    if len(args) == 1:
        n = args[0]
        i = 0
        while i < n:
            yield round(i, 2)
            i += 1
    elif len(args) == 2:
        i,n = args
        while i < n:
            yield round(i, 2)
            i += 1
    elif len(args)== 3:
        i,n,j = args
        if j==0:
            raise ValueError("El incremento no puede ser 0.")
        elif j>0:
            while i < n:
                yield round(i, 2)
                i += j
        else:
            while i > n:
                yield round(i, 2)
                i += j
    else:
        raise ValueError("Se esperan de 1 a 3 argumentos.")
        

**Ejercicio:** Escribe una función llamdada `linspace_with_arange` que sea como `np.linspace` pero que esté implementada con una única invocación de `np.arange`.

In [40]:
def linspace_with_arange(s,st,n=50):
    if n<=0   and not n.isinstance(int):
        raise ValueError()
    salto = (st-s) / (n-1)
    return np.arange(s,st+(salto/2),salto)

In [49]:
linspace_with_arange(2,5,15)

array([2.        , 2.21428571, 2.42857143, 2.64285714, 2.85714286,
       3.07142857, 3.28571429, 3.5       , 3.71428571, 3.92857143,
       4.14285714, 4.35714286, 4.57142857, 4.78571429, 5.        ])

In [44]:
print(np.arange(1, 2, 0.1))
print(np.linspace(1, 1.9, 10))

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


**Ejercicio:** Escribe una función llamada `arange_with_linspace` que sea como `np.arange` pero que esté implementada con una única invocación de `np.linspace`.

In [46]:
def arange_with_linspace(s,st,salto):
    if salto == 0 and not salto.isinstance((int,float)):
        raise ValueError()
    num = int((st-s)/salto)
    return np.linspace(s,st-salto,num)


In [50]:
np.arange(2,5,.3)

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7])

In [51]:
arange_with_linspace(2,5,.3)

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7])

## Generación de números aleatorios

In [ ]:
np.random.random()

In [ ]:
np.random.random()

In [ ]:
np.random.random()

In [ ]:
np.random.random(10)

Instala `matplotlib`, lo usaremos un poco pero más adelante discutiremos los detalles.

In [ ]:
import matplotlib as mpl
import matplotlib.pyplot as plt

In [ ]:
fig, ax = plt.subplots()
x = np.random.random(100)
ax.hist(
    x,
    bins=50,
)
ax.set(
    title="Histograma de números aleatorios con `np.random.random`",
);

In [ ]:
fig, ax = plt.subplots()
x = np.random.random(1000)
ax.hist(
    x,
    bins=50,
)
ax.set(
    title="Histograma de números aleatorios con `np.random.random`",
    xlim=(0,1),
);

In [ ]:
np.random.random((10, 3))

In [ ]:
np.random.random((3,4,5))

In [ ]:
X = np.random.random((3,3))
X

In [ ]:
fig, ax = plt.subplots()
x = np.random.random(1000)
y = np.random.random(1000)
ax.hist2d(
    x,
    y,
    bins=(50,50),
);
ax.set(
    title="Histograma de números aleatorios con `np.random.random`",
    xlim=(0,1),
    ylim=(0,1),
);

In [ ]:
np.random.normal(0, 1, 10)

In [ ]:
fig, ax = plt.subplots()
n = 100
x = np.random.normal(0, 1, n)
ax.hist(
    x,
    bins=50,
)
ax.set(
    title="Histograma de números aleatorios con `np.random.normal`",
    xlim=(-3.5,3.5),
);

In [ ]:
fig, ax = plt.subplots()
n = 100
x = np.random.normal(0, 1, n)
y = np.random.normal(0, 1, n)
ax.hist2d(
    x,
    y,
    bins=(50,50),
)
ax.set(
    title="Histograma de números aleatorios con `np.random.normal`",
    xlim=(-3.5,3.5),
    ylim=(-3.5,3.5),
);

## Sobre tipos de datos


| **Tipo**   | **Descripción**                                                               |
|------------|-------------------------------------------------------------------------------|
| bool_      | Booleano (True o False) almacenado como un byte                               |
| int_       | Tipo de entero por defecto (normalmente int64 o int32)                        |
| intc       | Igual que int en C (normalmente int32 o int64)                                |
| intp       | Entero usado para índices (igual que ssize_t en C; normalmente int32 o int64) |
| int8       | Byte (–128 al 127)                                                            |
| int16      | Entero (–32768 al 32767)                                                      |
| int32      | Entero (–2147483648 al 2147483647)                                            |
| int64      | Entero (–9223372036854775808 al 9223372036854775807)                          |
| uint8      | Entero sin signo (0 al 255)                                                   |
| uint16     | Entero sin signo (0 al 65535)                                                 |
| uint32     | Entero sin signo (0 al 4294967295)                                            |
| uint64     | Entero sin signo (0 al 18446744073709551615)                                  |
| float_     | Equivalente a float64                                                         |
| float16    | Flotante de precisión media (16 bits)                                         |
| float32    | Flotante simple (32 bits)                                                     |
| float64    | Flotante doble (64 bits)                                                      |
| complex_   | Equivalente a complex128                                                      |
| complex64  | Número complejo (dos floats simples)                                          |
| complex128 | Número complejo (dos floats dobles)                                           |